// dietData.js

export const dietPlans = {
  weight_loss: [
    [
      "Monday",
      "One bowl of Poha + 1 glass of milk",
      "Handful of nuts",
      "1 bowl of brown rice with dal + salad + 1 bowl Bhindi",
      "1 Apple + 1 cup of green tea/black coffee",
      "Two chapatis + 1 bowl of Jeera Aloo",
    ],
    [
      "Tuesday",
      "Omelette with two brown bread + one glass of milk",
      "1 bowl fruit salad + 1 glass coconut water",
      "1 bowl rajma + 1 bowl aloo gobhi + 1 bowl rice + 1 chapatti + 1 bowl cucumber raita",
      "1 cup tea/coffee + 1 cup papri chaat",
      "1 bowl lauki kofta + 2 chapati",
    ],
    [
      "Wednesday",
      "Namkeen Dalia + 1 apple",
      "One glass of fruit smoothie",
      "1 bowl paneer curry + 1 bowl boiled rice + 2 chapatti + salad",
      "1 cup tea/coffee + 1 cup aloo chaat",
      "1 bowl matar & mushroom curry + 2 chapati",
    ],
    [
      "Thursday",
      "Moong dal Cheela + 1 glass of milk",
      "One bowl yogurt",
      "1 bowl palak paneer + 1 bowl rice + 1 chapatti + salad",
      "1 cup tea/coffee + 1 cup boiled chana chat",
      "One bowl bottle gourd curry + 2 chapati",
    ],
    [
      "Friday",
      "1 bowl of oats + 1 glass of milk",
      "One glass of coconut water",
      "1 bowl paneer curry + 1 bowl dal + 1 bowl rice + salad",
      "1 cup mur-more chat + 1 cup tea/coffee",
      "1 bowl mustard greens + 2 chapati",
    ],
    [
      "Saturday",
      "Veggie stuffed omelet + 1 glass of milk",
      "Handful of seeds or nuts",
      "1 bowl boiled rice + 2 chapatti + 1 bowl dal + salad + 1 bowl ghia raita",
      "1 apple + 1 cup green tea/black coffee",
      "1 bowl of paneer curry + 2 chapatti",
    ],
    [
      "Sunday",
      "Besan Chila + 1 glass milk",
      "1 Apple",
      "1 bowl soya bean curry + 1 bowl tinda + 2 chapatti + salad",
      "1 cup boiled masala corn + 1 cup tea/coffee",
      "1 bowl mix veg + 2 chapatti",
    ],
  ],

  weight_gain: [
    [
      "Sunday",
      "2 egg brown bread sandwich + green chutney + 1 cup milk + nuts",
      "1 cup banana shake",
      "1 cup arhar dal + 1 cup potato curry + 3 chapatti + 1/2 cup rice + 1/2 cup low-fat curd + salad",
      "1 cup strawberry smoothie + 1 cup vegetable poha",
      "1.5 cup paneer butter masala + 3 chapatti + salad",
    ],
    [
      "Monday",
      "3 onion stuffed parantha + 1 cup curd + nuts",
      "1 cup mango shake",
      "1 cup moong dal + 1 cup potato and cauliflower vegetable + 3 chapatti + 1/2 cup rice + salad",
      "1 cup pomegranate juice + 2 butter toasted bread",
      "1 cup beans potato vegetable + 3 chapatti + salad",
    ],
    [
      "Tuesday",
      "3 paneer stuffed besan cheela + green chutney + 1 cup curd + nuts",
      "1 apple smoothie with maple syrup",
      "1 cup masoor dal + 1 cup calocasia + 3 chapatti + 1/2 cup rice + 1 cup low-fat curd + salad",
      "1 cup tomato soup with bread crumbs + 1 cup aloo chaat",
      "1 cup carrot peas vegetable + 3 chapatti + salad",
    ],
    [
      "Wednesday",
      "1.5 cup vegetable bread upma + 1 cup milk + nuts",
      "1 cup ripe banana with ghee",
      "1 cup rajma curry + 1 cup spinach potato + 3 chapatti + 1/2 cup rice + salad",
      "1 cup vegetable juice + 1 cup upma",
      "1.5 cup parwal vegetable + 3 chapatti + salad",
    ],
    [
      "Thursday",
      "2 cucumber potato sandwich + green chutney + 1 orange juice + nuts",
      "1 cup buttermilk + sweet potato chaat",
      "1 cup white chana + 3 chapatti + 1/2 cup rice + salad",
      "1 cup almond milk + banana",
      "1 cup cauliflower potato vegetable + 3 chapatti + salad",
    ],
    [
      "Friday",
      "2 cup vegetable poha + 1 cup curd + nuts",
      "2 cups watermelon juice",
      "1 cup chana dal + 1 cup bhindi vegetable + 3 chapatti + 1/2 cup rice + salad",
      "1 cup sprouts salad + 2 potato cheela + green chutney",
      "1 cup peas mushroom vegetable + 3 chapatti + salad",
    ],
    [
      "Saturday",
      "3 vegetable suji cheela + 1 cup strawberry shake + nuts",
      "1 cup coconut water + 1 cup pomegranate",
      "1 cup mix dal + 1 cup soybean curry + 3 chapatti + 1/2 cup curd + salad",
      "1 cup fruit salad + 4 vegetable cutlets + green chutney",
      "1 cup karela vegetable + 3 chapatti + salad",
    ],
  ],

  non_veg_weight_loss: [
    [
      "Monday",
      "Oatmeal with berries + 1 boiled egg",
      "Greek yogurt with honey",
      "Grilled chicken salad with mixed greens",
      "1 orange",
      "Steamed fish with veggies",
    ],
    [
      "Tuesday",
      "Scrambled eggs with spinach",
      "Handful of almonds",
      "Quinoa salad with chickpeas",
      "1 apple",
      "Grilled turkey breast with broccoli",
    ],
    [
      "Wednesday",
      "Avocado toast with poached egg",
      "Cottage cheese with pineapple",
      "Baked chicken with asparagus",
      "1 pear",
      "Zucchini noodles with marinara sauce",
    ],
    [
      "Thursday",
      "Smoothie with spinach, banana, and protein powder",
      "Sliced cucumber with hummus",
      "Salmon salad with mixed greens",
      "1 grapefruit",
      "Grilled shrimp with zucchini",
    ],
    [
      "Friday",
      "Chia pudding with berries",
      "Carrot sticks with guacamole",
      "Lentil soup with chicken",
      "1 apple",
      "Baked tilapia with steamed broccoli",
    ],
    [
      "Saturday",
      "Vegetable omelet + 1 slice whole-grain toast",
      "Greek yogurt with mixed berries",
      "Stuffed bell peppers with ground turkey",
      "1 orange",
      "Chicken stir-fry with bell peppers",
    ],
    [
      "Sunday",
      "Protein pancakes + 1 tablespoon peanut butter",
      "Handful of walnuts",
      "Tuna salad with chickpeas",
      "1 banana",
      "Grilled steak with mixed vegetables",
    ],
  ],

  non_veg_weight_gain: [
    [
      "Sunday",
      "Chicken sandwich with avocado + 1 cup milk",
      "Protein shake",
      "Grilled salmon with quinoa",
      "Banana with peanut butter",
      "Pasta with chicken and cheese",
    ],
    [
      "Monday",
      "Egg and cheese omelet",
      "Smoothie with spinach and protein powder",
      "Chicken curry with rice",
      "Yogurt with granola",
      "Beef stir-fry with vegetables",
    ],
    [
      "Tuesday",
      "Breakfast burrito with eggs, beans, and cheese",
      "Protein bar",
      "Teriyaki chicken with rice",
      "Mixed fruit salad",
      "Shrimp tacos with avocado",
    ],
    [
      "Wednesday",
      "French toast with maple syrup and bacon",
      "Cottage cheese with peaches",
      "Pork chops with sweet potatoes",
      "1 cup mixed nuts",
      "Salmon burgers with whole-grain bun",
    ],
    [
      "Thursday",
      "Omelet with smoked salmon and cream cheese",
      "Handful of almonds",
      "Chicken Alfredo pasta",
      "1 apple with almond butter",
      "Steak with mashed potatoes",
    ],
    [
      "Friday",
      "Scrambled eggs with sausage",
      "Smoothie with banana and protein powder",
      "Chili con carne with beans",
      "1 cup yogurt with honey",
      "Meatloaf with mashed vegetables",
    ],
    [
      "Saturday",
      "Breakfast sandwich with egg and cheese",
      "Greek yogurt with granola",
      "BBQ chicken with coleslaw",
      "1 pear",
      "Spaghetti with meatballs",
    ],
  ],
};
